### ISSUE TITLE
Example how to exclude scenes from the Back Stack [Android]

### ISSUE THREAD

**Issue by sytolk** [Johan-dutoit/RNN-StarterKit-V2#2]
I'm stuck with this in v.1 of RNN. My flow:
Screen A: TabBasedApp -> Screen B: Modal -> Dismiss modal (show screen A)
As a result Android Back button will show screen B but after dismiss of Modal screen B I want to exclude this screen from BackStack.
It's have native Java implementation to exclude Activity/Fragment from Android BackStack and if it's not exist I think this is very important to be implemented in new v.2 RNN.

**Comment by Johan-dutoit** [comment]
I'm not experiencing this on either v1 or v2.  However, I believe you should create the issue on the react-native-navigate repo directly to get better support.

**Comment by sytolk** [comment]
Yes I have already done. 
https://github.com/wix/react-native-navigation/issues/1793
