### ISSUE TITLE
Example for i18n localization reloading

### ISSUE THREAD

**Issue by sytolk** [Johan-dutoit/RNN-StarterKit-V2#4]
Is this issue is fixed in v.2 of RNN?
https://github.com/wix/react-native-navigation/issues/1718

I can see i18n integration here:
https://github.com/wix/react-native-navigation/issues/205

**Comment by Johan-dutoit** [comment]
Please refrain from posting `react-native-navigation` issues here.  This repo has no official ties with `react-native-navigation`.  

As I prefer to use `react-native-navigation` above the other solutions, I thought I'd share my starter project.  I have no idea if those issues have been fixed.
